### PR TITLE
Fixed compatibility with IE

### PR DESCRIPTION
**Pull request by jonahbron**
These small changes fix some nuances in how IE handles events and XHR.

### CODE REVIEW

**Comment by mpetazzoni** [comment]
Can you cleanup the commit history though around the polyfill add/remove? Thanks!

**Comment by jonahbron** [comment]
@mpetazzoni All right, recreated the branch and cherry-picked.

**Comment by mpetazzoni** [comment]
Thanks!

**Comment by jonahbron** [comment]
@mpetazzoni Any chance you could publish a new release with these changes?

**Comment by mpetazzoni** [comment]
0.4.4 is published!

**Comment by jonahbron** [comment]
Thanks! :smile:

**Pull request merged**
