### PR TITLE
Added support for connection close detection

### PR DESCRIPTION
**Pull request by jonahbron**
My application needs to detect when the request has closed, this adds support for that.

### CODE REVIEW

**Comment by mpetazzoni** [comment]
Thanks for the contribution. Is that not already covered by the `load`, `abort` and `error` events though?

**Comment by jonahbron** [comment]
@mpetazzoni I added listeners to all of the events, and none of them seemed to trigger when the request closed.  If you have a different idea of how you'd like that event triggered, I'd be happy to modify my PR.

**Comment by mpetazzoni** [comment]
Interesting. What browser are you testing with? It looks like IE versions older than IE10 don't support the new ProgressEvent interface:

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#Browser_compatibility

If that's the case, then we can certainly support the `onreadystatechange` event, but if so then we need proper support since it would be the only kind of event fired. The handler for it should thus correctly dispatch to the other handlers as needed based on the values of `this.xhr.readyState` and `this.xhr.status`.

**Comment by jonahbron** [comment]
I tested with Chrome.  Everything else works fine, and I did get other readystatechange events, just none for the close event.

**Comment by jonahbron** [comment]
the CONNECTING and OPEN ready states trigger the event (lines 171 and 104, respectively), and CLOSED does trigger if the stream fails (line 93).  This change only makes sure it's triggered if the connection is closed _successfully_.

**Comment by jonahbron** [comment]
If you think it makes more sense, I could move the `_setReadyState` call to the end of `_onStreamLoaded`, so that CLOSED is triggered after the last chunk is loaded.  But it made sense to me to base the CLOSED ready state on the XHR closed ready state.

**Comment by jonahbron** [comment]
And just to be clear, I'm not _adding_ the readystatechange event to the library.  It's already happening (line 85).  I'm merely adding a trigger for a scenario that's not currently supported.

**Comment by mpetazzoni** [comment]
Makes sense. Thanks for the explanation. Looks good then!

**Comment by jonahbron** [comment]
Awesome, thanks!

**Pull request merged**
