### PR TITLE
IE11 fixes

### PR DESCRIPTION
**Pull request by jonahbron**
These changes seem to make this library operational with IE11.

### CODE REVIEW

**Comment by mpetazzoni** [comment]
Can you elaborate on why `new Event()` doesn't work? Is that an IE11 restriction? I'd like to keep this library dependency-free.

**Comment by jonahbron** [comment]
IE does not support some of the event names in the application (including but not limited to `readystatechange`).  CustomEvents is not a completely new thing, it's part of the browser API, with the purpose of creating custom event objects.  The dependency is **ONLY** a polyfill.

https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent

If you're shooting for dependency-free, I'd be happy to remove the dependency, instead documenting that the polyfill must be added to an application for IE compatibility.

**Comment by mpetazzoni** [comment]
Yeah I'd prefer to keep it dependency-free, especially if CustomEvent is part of the browser API. People are then free to add the polyfills they need to bridge the gap in browser compatibility if they use browsers that don't implement the full spec (note that Edge does, for example, but not IE11 as you pointed out).

**Comment by jonahbron** [comment]
All righty, will do.

**Comment by jonahbron** [comment]
Added PR #4 which removes the dependency.

**Pull request closed without merging**
